apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  valuesContent: |-
    deployment:
      replicas: 2
    podDisruptionBudget:
      minAvailable: 1
    rbac:
      enabled: true
    ssl:
      enabled: true
    metrics:
      prometheus:
        enabled: true
    service:
      spec:
        externalTrafficPolicy: Local
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
