apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
      - peer-address: 172.16.42.1
        peer-asn: 65530
        my-asn: 65530
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 172.16.43.0/27
