apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: system
  source:
    path: rook-ceph
    repoURL: https://github.com/corvus-ch/damp-lab-1081.git
    targetRevision: HEAD
