apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: system
  source:
    path: rook-ceph
    repoURL: https://github.com/corvus-ch/damp-lab-1081.git
    targetRevision: HEAD
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: kube-system
spec:
  repo: https://charts.rook.io/release
  chart: rook-ceph
  version: v1.5.4
  targetNamespace: rook-ceph
  valuesContent: |-
    controller:
      replicaCount: 2
      service:
        externalTrafficPolicy: Local
