apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: haeusler.christian@mac.com
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: haeusler.christian@mac.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
